// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAscGq823l5U9AelMmF3Vob4JY8W1XxCRc',
    appId: '1:46644952101:web:45a4f8580613c05dd393cc',
    messagingSenderId: '46644952101',
    projectId: 'evently-app-7e27e',
    authDomain: 'evently-app-7e27e.firebaseapp.com',
    storageBucket: 'evently-app-7e27e.firebasestorage.app',
    measurementId: 'G-T91QWPLX8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHt9RGNbxO3OLP7x-z914haYITpgeminM',
    appId: '1:46644952101:android:40887594897cf3d2d393cc',
    messagingSenderId: '46644952101',
    projectId: 'evently-app-7e27e',
    storageBucket: 'evently-app-7e27e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzMZteakbE_tJlY7wUFbTN0FH40gCOEW8',
    appId: '1:46644952101:ios:fb278e521fee3af7d393cc',
    messagingSenderId: '46644952101',
    projectId: 'evently-app-7e27e',
    storageBucket: 'evently-app-7e27e.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzMZteakbE_tJlY7wUFbTN0FH40gCOEW8',
    appId: '1:46644952101:ios:fb278e521fee3af7d393cc',
    messagingSenderId: '46644952101',
    projectId: 'evently-app-7e27e',
    storageBucket: 'evently-app-7e27e.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAscGq823l5U9AelMmF3Vob4JY8W1XxCRc',
    appId: '1:46644952101:web:01975486a768aa16d393cc',
    messagingSenderId: '46644952101',
    projectId: 'evently-app-7e27e',
    authDomain: 'evently-app-7e27e.firebaseapp.com',
    storageBucket: 'evently-app-7e27e.firebasestorage.app',
    measurementId: 'G-51Y99P5SBZ',
  );
}
